"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

import aspn23_lcm


class measurement_direction_of_motion_3d(object):
    """Direction of motion represented as a unit vector."""

    __slots__ = [
        "icd_measurement_direction_of_motion_3d",
        "header",
        "time_of_validity",
        "reference_frame",
        "obs",
        "error_vector",
        "covariance",
        "error_model",
        "num_error_model_params",
        "error_model_params",
        "num_integrity",
        "integrity",
    ]

    __typenames__ = [
        "int8_t",
        "aspn23_lcm.type_header",
        "aspn23_lcm.type_timestamp",
        "int8_t",
        "double",
        "double",
        "double",
        "int8_t",
        "int32_t",
        "double",
        "int16_t",
        "aspn23_lcm.type_integrity",
    ]

    __dimensions__ = [
        None,
        None,
        None,
        None,
        [3],
        [3],
        [2, 2],
        None,
        None,
        ["num_error_model_params"],
        None,
        ["num_integrity"],
    ]

    REFERENCE_FRAME_ECI = 0
    """ Direction of motion with respect to earth-centered inertial (ECi) frame, expressed in an earth-centered inertial frame. See also ECi coordinate frame definition for x, y, and z definitions. """
    REFERENCE_FRAME_ECEF = 1
    """ Direction of motion with respect to earth-fixed frame expressed in earth-centered, earth-fixed (ECEF) frame. See also ECEF coordinate frame definition for x, y, and z definitions. """
    REFERENCE_FRAME_NED = 2
    """ Local level, geodetic velocity: Velocity with respect to earth-fixed frame expressed in the North-East-Down (NED), local level frame. See also NED coordinate frame definition for N, E, and D definitions. """
    REFERENCE_FRAME_SENSOR = 3
    """ Direction of motion with respect to earth-fixed frame expressed in sensor coordinate frame. Sensor coordinate frame is defined in sensor metadataHeader. """
    ERROR_MODEL_NONE = 0
    """ No additional error model provided (num_error_model_params = 0). """

    def __init__(self):
        self.icd_measurement_direction_of_motion_3d = 0
        """
        Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
        LCM Type: int8_t
        """

        self.header = aspn23_lcm.type_header()
        """
        Description: Standard ASPN measurement header
        Units: none
        LCM Type: aspn23_lcm.type_header
        """

        self.time_of_validity = aspn23_lcm.type_timestamp()
        """
        Description: Time at which the measurement is considered to be valid
        Units: none
        LCM Type: aspn23_lcm.type_timestamp
        """

        self.reference_frame = 0
        """
        Defines measurement reference.
        LCM Type: int8_t
        """

        self.obs = [0.0 for dim0 in range(3)]
        """
        Description: Direction of motion represented as a unit vector
        Units: none
        LCM Type: double[3]
        """

        self.error_vector = [0.0 for dim0 in range(3)]
        """
        Description: Error is expressed as rotation uncertainty about two axes, error_vector and and a second error vector that is orthogonal to both the obs vector and the error_vector
        Units: none
        LCM Type: double[3]
        """

        self.covariance = [[0.0 for dim1 in range(2)] for dim0 in range(2)]
        """
        Description: Error is expressed as rotation uncertainty about the following two axes: 1) error_vector, and 2) a second error vector that is orthogonal to both the obs direction vector and the error_vector
        Units: rad^2
        LCM Type: double[2][2]
        """

        self.error_model = 0
        """
        Defines an optional error model for other than zero-mean, additive, white Gaussian noise (AWGN).
        LCM Type: int8_t
        """

        self.num_error_model_params = 0
        """
        Description: Number of parameters required for the error model chosen
        Units: none
        LCM Type: int32_t
        """

        self.error_model_params = []
        """
        Description: Error model parameters that characterize the optional error model
        Units: various
        LCM Type: double[num_error_model_params]
        """

        self.num_integrity = 0
        """
        Description: Number of integrity values
        Units: none
        LCM Type: int16_t
        """

        self.integrity = []
        """
        Description: Measurement integrity. Includes the integrity method used and an integrity value (which is to be interpreted based upon the integrity method). The intent of allowing num_integrity > 1 is to report multiple integrity values based on multiple integrity methods
        Units: none
        LCM Type: aspn23_lcm.type_integrity[num_integrity]
        """

    def encode(self):
        buf = BytesIO()
        buf.write(measurement_direction_of_motion_3d._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.icd_measurement_direction_of_motion_3d))
        assert (
            self.header._get_packed_fingerprint()
            == aspn23_lcm.type_header._get_packed_fingerprint()
        )
        self.header._encode_one(buf)
        assert (
            self.time_of_validity._get_packed_fingerprint()
            == aspn23_lcm.type_timestamp._get_packed_fingerprint()
        )
        self.time_of_validity._encode_one(buf)
        buf.write(struct.pack(">b", self.reference_frame))
        buf.write(struct.pack(">3d", *self.obs[:3]))
        buf.write(struct.pack(">3d", *self.error_vector[:3]))
        for i0 in range(2):
            buf.write(struct.pack(">2d", *self.covariance[i0][:2]))
        buf.write(struct.pack(">bi", self.error_model, self.num_error_model_params))
        buf.write(
            struct.pack(
                ">%dd" % self.num_error_model_params,
                *self.error_model_params[: self.num_error_model_params]
            )
        )
        buf.write(struct.pack(">h", self.num_integrity))
        for i0 in range(self.num_integrity):
            assert (
                self.integrity[i0]._get_packed_fingerprint()
                == aspn23_lcm.type_integrity._get_packed_fingerprint()
            )
            self.integrity[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != measurement_direction_of_motion_3d._get_packed_fingerprint():
            raise ValueError("Decode error")
        return measurement_direction_of_motion_3d._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = measurement_direction_of_motion_3d()
        self.icd_measurement_direction_of_motion_3d = struct.unpack(">b", buf.read(1))[
            0
        ]
        self.header = aspn23_lcm.type_header._decode_one(buf)
        self.time_of_validity = aspn23_lcm.type_timestamp._decode_one(buf)
        self.reference_frame = struct.unpack(">b", buf.read(1))[0]
        self.obs = struct.unpack(">3d", buf.read(24))
        self.error_vector = struct.unpack(">3d", buf.read(24))
        self.covariance = []
        for i0 in range(2):
            self.covariance.append(struct.unpack(">2d", buf.read(16)))
        self.error_model, self.num_error_model_params = struct.unpack(
            ">bi", buf.read(5)
        )
        self.error_model_params = struct.unpack(
            ">%dd" % self.num_error_model_params,
            buf.read(self.num_error_model_params * 8),
        )
        self.num_integrity = struct.unpack(">h", buf.read(2))[0]
        self.integrity = []
        for i0 in range(self.num_integrity):
            self.integrity.append(aspn23_lcm.type_integrity._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if measurement_direction_of_motion_3d in parents:
            return 0
        newparents = parents + [measurement_direction_of_motion_3d]
        tmphash = (
            0xEF0CE4EDB7929076
            + aspn23_lcm.type_header._get_hash_recursive(newparents)
            + aspn23_lcm.type_timestamp._get_hash_recursive(newparents)
            + aspn23_lcm.type_integrity._get_hash_recursive(newparents)
        ) & 0xFFFFFFFFFFFFFFFF
        tmphash = (
            ((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)
        ) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if measurement_direction_of_motion_3d._packed_fingerprint is None:
            measurement_direction_of_motion_3d._packed_fingerprint = struct.pack(
                ">Q", measurement_direction_of_motion_3d._get_hash_recursive([])
            )
        return measurement_direction_of_motion_3d._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(
            ">Q", measurement_direction_of_motion_3d._get_packed_fingerprint()
        )[0]
