"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

import aspn23_lcm


class metadata_BeiDou_ephemeris(object):
    """
    BeiDou Ephemeris describing satellite locations. Definitions and usage are
    covered in BDS-SIS-ICD-BII-3.0, February 2019,
    """

    __slots__ = [
        "icd_metadata_BeiDou_ephemeris",
        "info",
        "time_of_validity",
        "prn",
        "clock",
        "orbit",
        "t_gd1",
        "t_gd2",
        "aodc",
        "aode",
    ]

    __typenames__ = [
        "int8_t",
        "aspn23_lcm.type_metadataheader",
        "aspn23_lcm.type_timestamp",
        "int32_t",
        "aspn23_lcm.type_satnav_clock",
        "aspn23_lcm.type_kepler_orbit",
        "double",
        "double",
        "int16_t",
        "int16_t",
    ]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.icd_metadata_BeiDou_ephemeris = 0
        """
        Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
        LCM Type: int8_t
        """

        self.info = aspn23_lcm.type_metadataheader()
        """
        Description: Standard ASPN metadata header
        Units: none
        LCM Type: aspn23_lcm.type_metadataheader
        """

        self.time_of_validity = aspn23_lcm.type_timestamp()
        """
        Description: Time at which the measurement is considered to be valid
        Units: none
        LCM Type: aspn23_lcm.type_timestamp
        """

        self.prn = 0
        """
        Description: Satellite PRN number
        Units: none
        LCM Type: int32_t
        """

        self.clock = aspn23_lcm.type_satnav_clock()
        """
        Description: GNSS broadcast parameters required to calculate sv clock corrections
        Units: none
        LCM Type: aspn23_lcm.type_satnav_clock
        """

        self.orbit = aspn23_lcm.type_kepler_orbit()
        """
        Description: Keplerian orbit parameters required to calculate satellite position
        Units: none
        LCM Type: aspn23_lcm.type_kepler_orbit
        """

        self.t_gd1 = 0.0
        """
        Description: Group delay differential for B1I user
        Units: s
        LCM Type: double
        """

        self.t_gd2 = 0.0
        """
        Description: Group delay differential for B2I user
        Units: s
        LCM Type: double
        """

        self.aodc = 0
        """
        Description: Age of data, clock is updated at start of each hour in BDT per table 5-6 in BDS-SIS-ICD-BII-3.0
        Units: none
        LCM Type: int16_t
        """

        self.aode = 0
        """
        Description: Age of data, ephemeris is updated at start of each hour in BDT per table 5-8 in BDS-SIS-ICD-BII-3.0
        Units: none
        LCM Type: int16_t
        """

    def encode(self):
        buf = BytesIO()
        buf.write(metadata_BeiDou_ephemeris._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.icd_metadata_BeiDou_ephemeris))
        assert (
            self.info._get_packed_fingerprint()
            == aspn23_lcm.type_metadataheader._get_packed_fingerprint()
        )
        self.info._encode_one(buf)
        assert (
            self.time_of_validity._get_packed_fingerprint()
            == aspn23_lcm.type_timestamp._get_packed_fingerprint()
        )
        self.time_of_validity._encode_one(buf)
        buf.write(struct.pack(">i", self.prn))
        assert (
            self.clock._get_packed_fingerprint()
            == aspn23_lcm.type_satnav_clock._get_packed_fingerprint()
        )
        self.clock._encode_one(buf)
        assert (
            self.orbit._get_packed_fingerprint()
            == aspn23_lcm.type_kepler_orbit._get_packed_fingerprint()
        )
        self.orbit._encode_one(buf)
        buf.write(struct.pack(">ddhh", self.t_gd1, self.t_gd2, self.aodc, self.aode))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != metadata_BeiDou_ephemeris._get_packed_fingerprint():
            raise ValueError("Decode error")
        return metadata_BeiDou_ephemeris._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = metadata_BeiDou_ephemeris()
        self.icd_metadata_BeiDou_ephemeris = struct.unpack(">b", buf.read(1))[0]
        self.info = aspn23_lcm.type_metadataheader._decode_one(buf)
        self.time_of_validity = aspn23_lcm.type_timestamp._decode_one(buf)
        self.prn = struct.unpack(">i", buf.read(4))[0]
        self.clock = aspn23_lcm.type_satnav_clock._decode_one(buf)
        self.orbit = aspn23_lcm.type_kepler_orbit._decode_one(buf)
        self.t_gd1, self.t_gd2, self.aodc, self.aode = struct.unpack(
            ">ddhh", buf.read(20)
        )
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if metadata_BeiDou_ephemeris in parents:
            return 0
        newparents = parents + [metadata_BeiDou_ephemeris]
        tmphash = (
            0xD9732D27913FEC47
            + aspn23_lcm.type_metadataheader._get_hash_recursive(newparents)
            + aspn23_lcm.type_timestamp._get_hash_recursive(newparents)
            + aspn23_lcm.type_satnav_clock._get_hash_recursive(newparents)
            + aspn23_lcm.type_kepler_orbit._get_hash_recursive(newparents)
        ) & 0xFFFFFFFFFFFFFFFF
        tmphash = (
            ((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)
        ) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if metadata_BeiDou_ephemeris._packed_fingerprint is None:
            metadata_BeiDou_ephemeris._packed_fingerprint = struct.pack(
                ">Q", metadata_BeiDou_ephemeris._get_hash_recursive([])
            )
        return metadata_BeiDou_ephemeris._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", metadata_BeiDou_ephemeris._get_packed_fingerprint())[
            0
        ]
